/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACardMeta: typeof import('ant-design-vue/es')['CardMeta']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AFloatButton: typeof import('ant-design-vue/es')['FloatButton']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    FloatButton: typeof import('./src/components/FloatButton.vue')['default']
    LoginPopup: typeof import('./src/components/LoginPopup.vue')['default']
    PortalComponent: typeof import('./src/components/PortalComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
